### ISSUE TITLE
Docker actions broken after moving dockerfiles

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/contrib#129]
The repo here is not even checked out -> no context/dockerfile available 

Please always try to check changes in the nightlies on the day after untested changes (even if two people look over it ;) , otherwise they get forgotten until other people need it.

**Comment by timosachsenberg** [comment]
@KyowonJeong I can take a look at it.

**Comment by timosachsenberg** [comment]
Ah sorry. I thought that was the idea. That no checkout is needed anymore because the repo is always in the context.

Will try something like:
https://github.com/OpenMS/contrib/pull/130

> The repo here is not even checked out -> no context/dockerfile available
> 
> Please always try to check changes in the nightlies on the day after untested changes (even if two people look over it ;) , otherwise they get forgotten until other people need it.

**Comment by cbielow** [comment]
https://github.com/OpenMS/contrib/.github/workflows desperately deserves a `readme.md` to know what is going on here

**Comment by timosachsenberg** [comment]
I think these actions are not sooo bad as there is not much logic going on and all actions are documented.
I would probably also put comments into the action instead of a readme.md

**Comment by jpfeuffer** [comment]
I agree. It is basically git clone && docker buildx dockerfiles/ && docker push ghcr.io/containername.
Rest is authentication and branching logic (which could/should be removed by mounting the checked out files into the container)

And their names and steps are rather descriptive.

**Comment by timosachsenberg** [comment]
Could this error:
```
ERROR: failed to solve: executor failed running [/bin/sh -c git clone https://github.com/OpenMS/contrib.git --branch "$OPENMS_BRANCH" --single-branch &&     mkdir contrib-build &&     cd contrib-build &&     cmake -DBUILD_TYPE=ALL ../contrib &&     rm -rf archives src &&     cp -r . /contrib-build &&    cd /]: exit code: 1
Error: buildx failed with: ERROR: failed to solve: executor failed running [/bin/sh -c git clone https://github.com/OpenMS/contrib.git --branch "$OPENMS_BRANCH" --single-branch &&     mkdir contrib-build &&     cd contrib-build &&     cmake -DBUILD_TYPE=ALL ../contrib &&     rm -rf archives src &&     cp -r . /contrib-build &&    cd /]: exit code: 1
```

be because of the last cp failing?
```
> [8/9] RUN git clone https://github.com/OpenMS/contrib.git --branch "master" --single-branch &&     mkdir contrib-build &&     cd contrib-build &&     cmake -DBUILD_TYPE=ALL ../contrib &&     rm -rf archives src &&     cp -r . /contrib-build &&    cd /:
#11 878.6 -- 
#11 878.6 --   The contrib package has been built!
#11 878.6 --   You can now configure and build OpenMS!
#11 878.6 -- 
#11 878.6 -- 
#11 878.6 -- 
#11 878.6 -- Configuring done
#11 878.6 -- Generating done
#11 878.6 -- Build files have been written to: /contrib-build
#11 881.0 cp: ‘.’ and ‘/contrib-build/.’ are the same file
```
According to https://github.com/OpenMS/contrib/commit/dfb65f7a1e989c4a77aa4eb2c35725d1fbf52d45#diff-d24fa4b7951c106bd74f36ac7d88b8a737c65c9346d28d39b4a4b4b57608bb10R22
we are already in the contrib-build folder so I can probably just remove the cp?

**Comment by jpfeuffer** [comment]
Yes that seems to be a remainder of building it from the OpenMS directory.

**Comment by timosachsenberg** [comment]
ok.

if I also want to remove the clone:
```
# build contrib for the current checked out branch (e.g. the github action context)
RUN mkdir contrib-build && \
    cd contrib-build && \
    cmake -DBUILD_TYPE=ALL ../contrib && \
    rm -rf archives src && \
    cd /
```
what is the best/good way to do that?
use the default context (whole repo) and just pass the dockerfile as file?
```
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true # Will only build if this is not here
          file: ./dockerfiles/pyopenms/manylinux
          # context: "{{defaultContext}}" make the w
          build-args: |
            OPENMS_BRANCH=${{ steps.extract_branch.outputs.branch }}
            OPENMS_VERSION=${{ steps.tag_name.outputs.tag }}
          tags: |
            ghcr.io/openms/contrib_manylinux2014:${{ steps.tag_name.outputs.tag }}
```
but then also delete all sources to not push a contrib image with everything?
